name: Generate Event Screenshots

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run screenshot script
        run: node screenshot.js

      - name: Commit screenshots
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/*.png
          git commit -m "Generated event screenshots"
          git push
        continue-on-error: true
