name: Generate Event Page Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run screenshot script
        run: |
          echo "➡️ Loading page..."
          node screenshot.js

      - name: Commit and push screenshots
        run: |
          git config --global user.name "Kevin McHale"
          git config --global user.email "kmchale@romeoville.org"
          git add output/*.png
          git commit -m "Update screenshots [CI skip]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main

  deploy:
    needs: screenshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build dist folder with output files
        run: |
          mkdir -p dist
          cp output/*.png dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          publish_branch: gh-pages
